### ISSUE TITLE
raster catalogue

### ISSUE THREAD

**Issue by 80vs90** [Applied-GeoSolutions/geokit#101]
Originally reported by: **Pavel D (Bitbucket: [demiurge](https://bitbucket.org/demiurge), GitHub: [demiurge](https://github.com/demiurge))**

----------------------------------------

@remeryAGS can you provide a screenshot and data items for the current table, and maybe Brandan can come up with any improvements, which we can then implement.

----------------------------------------
- Bitbucket: https://bitbucket.org/appliedgeosolutions/geokit/issue/101

**Comment by demiurg** [comment]
looks good
