### ISSUE TITLE
need a new photo on the main Geokit page background

### ISSUE THREAD

**Issue by 80vs90** [Applied-GeoSolutions/geokit#103]
Originally reported by: **Bobby Braswell (Bitbucket: [rbraswell](https://bitbucket.org/rbraswell), GitHub: [rbraswell](https://github.com/rbraswell))**

----------------------------------------

need a new photo on the main Geokit page background (that doesn't say "**iStock by Getty Images**"

And that maybe looks cooler than that guy. That guy is funny and awesome in his own way. But let's think Earth as is Ecosystems more than Rocks.

I suggest that @rbraswell will work with @bglendenning

----------------------------------------
- Bitbucket: https://bitbucket.org/appliedgeosolutions/geokit/issue/103

**Comment by bglendenning** [comment]
Below-the-fold section has been removed, and signup form behavior & appearance has been updated to work with new page layout.

**Comment by demiurg** [comment]
very enhanced
