### ISSUE TITLE
progress status

### ISSUE THREAD

**Issue by 80vs90** [Applied-GeoSolutions/geokit#74]
Originally reported by: **Pavel D (Bitbucket: [demiurge](https://bitbucket.org/demiurge), GitHub: [demiurge](https://github.com/demiurge))**

----------------------------------------

* Job can be successfully submitted, "request is being processed" or it can fail to submit
* Submitted job can be
    * Assets being downloaded 
    * Products being processed
    * Products being aggregated

----------------------------------------
- Bitbucket: https://bitbucket.org/appliedgeosolutions/geokit/issue/74

**Comment by demiurg** [comment]
Status is being indicated by color now.
