### ISSUE TITLE
Aggregation metrics

### ISSUE THREAD

**Issue by 80vs90** [Applied-GeoSolutions/geokit#79]
Originally reported by: **Bobby Braswell (Bitbucket: [rbraswell](https://bitbucket.org/rbraswell), GitHub: [rbraswell](https://github.com/rbraswell))**

----------------------------------------

I think currently the raster aggregation metrics appear to be a little too much a part of the variable creation process. The user knows that the raster data source is remote from the web site and that the data are being aggregated. I think as part of the initial formulation of the request it should be apparent that the user wants mean, std, or whatever. Alternatively, it could just always be the mean and we could hide this altogether.

----------------------------------------
- Bitbucket: https://bitbucket.org/appliedgeosolutions/geokit/issue/79

**Comment by demiurg** [comment]
somehow things have been made to use mean if nothing is specified
