### ISSUE TITLE
Visualizations can be generic

### ISSUE THREAD

**Issue by 80vs90** [Applied-GeoSolutions/geokit#81]
Originally reported by: **Bobby Braswell (Bitbucket: [rbraswell](https://bitbucket.org/rbraswell), GitHub: [rbraswell](https://github.com/rbraswell))**

----------------------------------------

I think as we discussed, that the user shouldn't need to say what sort of visualization they want (by default), since you can detect whether something is space, time, or spacetime from the dimensions.

----------------------------------------
- Bitbucket: https://bitbucket.org/appliedgeosolutions/geokit/issue/81

**Comment by demiurg** [comment]
@80vs90 i think this is true?
