### ISSUE TITLE
Sieve lets users select layers that are still processing

### ISSUE THREAD

**Issue by 80vs90** [Applied-GeoSolutions/geokit#86]
Originally reported by: **Rick Emery (Bitbucket: [remeryAGS](https://bitbucket.org/remeryAGS), GitHub: [remeryAGS](https://github.com/remeryAGS))**

----------------------------------------

This is probably bad.

----------------------------------------
- Bitbucket: https://bitbucket.org/appliedgeosolutions/geokit/issue/86

**Comment by demiurg** [comment]
It's probably not toooooo bad.
